<template>
  <v-container>
    <v-row>
      <v-col cols="12" md="10">
        <v-card elevation="10" outlined>
          <v-card-text>
            <div class="text-h5 mb-1">Acuity Social November 2020 Project Update</div>
            <div class="subtitle-2 mb-4">1st November 2020 by Jonathan Brown</div>
            <div class="text-h6 mb-1">Sharding</div>
            <div class="body-2 mb-4">I've made a major architecture design decision for Acuity: each community built with Acuity can be its own parachain, with the Acuity chain as its parent. This has a number of advantages:
              <ul>
                <li>scalabilty - while a substrate blockchain does have </li>
              </ul>
            </div>
            <div class="text-h6 mb-1">Migration from PoA to NPoS</div>
            <div class="body-2 mb-4">The referendum to transition Acuity from Proof-of-authority to Nominated Proof-of-stake passed and was automatically enacted on 17th October.</div>
            <div class="body-2 mb-4">It is now possible become a nominator and stake your ACU by choosing which validators you think will perform well. Unfortunately it is still not possible to become a validator. The transaction to set validator session keys does not succeed. The four original PoA validators remain as the only validators. Enabling anyone to become a validator will require further investigation.</div>
            <div class="text-h6 mb-1">PoA validator profit automatically donated to treasury</div>
            <div class="body-2 mb-4">A side-effect of migrating to NPoS is that all the revenue generated by the four PoA validators was and continues to be donated automatically to the Acuity Treasury. The treasury balance currently stands at around 500k ACU.</div>
            <div class="body-2 mb-4">Anyone can make a proposal for Treasury spending. Each proposal must be approved by the Acuity Council before it can be enacted.</div>
            <div class="text-h6 mb-1">STEX</div>
            <div class="body-2 mb-4">It is now possible to trade ACU against ETH on <a target="_blank" href="https://app.stex.com/en/trade/pair/ETH/ACU">STEX</a>.</div>
            <div class="text-h6 mb-1">ACU / ETH Atomic Swap Exchange</div>
            <div class="body-2 mb-4">I am developing an Atomic Swap exchange that will be available this website. Substrate already has an Atomic Swap pallet available. This will enable fully permissionless trading of ACU enabling its free market value to be determined. It will function through simultaneous use of both the Polkadot and Metamask browser plugins. This exchange will be fully open source and available for other Polkadot chains to utilize.</div>
            <div class="body-2 mb-4">This is a much better approach to connecting Acuity to the Ethereum ecosystem than developing a "Wrapped ACU". Uniswap-style trading will be available via Polkaswap. Because Polkaswap is built on Polkadot the transaction fees will be significantly lower than Uniswap.</div>
          </v-card-text>
        </v-card>
      </v-col>
      <v-col cols="12" md="10">
        <v-card elevation="10" outlined>
          <v-card-text>
            <div class="text-h5 mb-1">Let's enable staking on the new Acuity Polkadot blockchain</div>
            <div class="subtitle-2 mb-4">25th September 2020 by Jonathan Brown</div>
            <div class="body-2 mb-4">
              <p>The Acuity blockchain uses standard Polkadot <a target="_blank" href="https://wiki.polkadot.network/docs/en/learn-consensus">consensus</a> and <a target="_blank" href="https://wiki.polkadot.network/docs/en/learn-governance">governance</a>.</p>

              <p>Just like Polkadot and Kusama, Acuity launched in proof-of-authority mode. We now need to switch to proof-of-stake. Polkadot and Kusama both launched with the Sudo pallet (god-mode) enabled and used this to call <a target="_blank" href="https://polkadot.js.org/api/substrate/extrinsics.html#forcenewera">staking.forceNewEra</a> to initiate this transition.</p>

              <p>However, as Acuity does not have the Sudo pallet enabled, it is necessary to make the staking.forceNewEra call via the proper governance mechanism. To this end I have created an Acuity Council <a target="_blank" href="https://polkadot.acuity.social/#/council/motions">motion</a>. This needs to be voted on by council members so that it can go to a general referendum. Please join the council and vote for this motion.</p>

              <p>There is currently another referendum in progress. Under normal circumstances only one referendum can be running at a time and each referendum takes 1 week. This means that the referendum to start staking cannot finish until 9th October. Then there is an enactment delay of 8 days. So staking will probably begin on 17th October. This will give us time for many validators to get ready.</p>

              <p>Once PoS has begun, any ACU that the current PoA accounts have accrued will be donated to the treasury.</p>

              <p>If you need any assistance with this process, please drop into the Staking channel on <a target="_blank" href="https://discordapp.com/invite/GxD7adN">Discord</a>.</p>

              <p>This is what I am currently considering including in the subsequent council proposal:
                <ul>
                  <li>Enable fast-track legislation: Polkadot governance has a fast-track mechanism that allows a proposal to be brought to referendum immediately, with a far shorter voting period than normal (3 days) and a near zero enactment period. This would enable me to propose system upgrades that could be enacted much more quickly.</li>
                  <li>Vest the project revenue: on MIX the project revenue was gradually <a target="_blank" href="https://docs.mix-blockchain.org/en/latest/issuance.html">released</a> at a ever-decreasing rate, ending October 18th 2022. The unreleased revenue was brought across to the new ACU blockchain, but it needs to be vested to match the original schedule.</li>
                  <li>Enable <router-link to="/trade">ACU</router-link> pallet: expose ACU to DeFi on Ethereum.</li>
                </ul>
              </p>
            </div>
          </v-card-text>
        </v-card>
      </v-col>
    </v-row>
  </v-container>
</template>

<script lang="ts">
  import Vue from 'vue'

  export default Vue.extend({
    name: 'Blog',

    data: () => ({
    }),
  })
</script>
